name: Label

on:
  pull_request:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Function
        run: |
          echo "${{ contains(github.event.pull_request.labels.*.name, 'bug ') }}"
          labels="${{ toJSON(github.event.pull_request.labels.*.name) }}"
          echo "$labels"
          version=""
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'invalid') }}" ]]; then
            echo "Label found, do something"
            version="-PVersionName=99.9.9 -PVersionCode=999"
          else
            version="-PVersionName=88.9.9 -PVersionCode=899"
            echo "Label not found, do something else"
          fi
          echo "$version"