name: Label

on:
  pull_request:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: echo "::set-output name=my_var::hello world"
      - name: Use Function
        run: |
          echo "${{ github.event.pull_request.labels.*.name }}"
          echo "${{ contains(github.event.pull_request.labels.*.name, 'test') }}"