name: Label

on:
  pull_request:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: echo "::set-output name=my_var::hello world"
      - name: Use Function
        run: |
          echo "${{ env.my_var }}"
          echo "${{ contains(env.my_var, 'world') }}" 
          echo "${{ read_file('README.md') }}"