name: FLUTTER_PUBLISH

on:
  release:
    types: [published]
env:
  flutter_version: "2.5.1"

jobs:
  publish_android_aar:
    runs-on: ubuntu-latest
    env:
      PUB_HOSTED_URL: https://pub.flutter-io.cn
      FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
    steps:
      - uses: actions/checkout@v1
        with:
          path: xiachufang_flutter
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        id: cache-flutter
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
    outputs:
      job-status: ${{ job.status }}
